import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import EnsureUserInDB  from "@/app/provider";
import QueryProvider from "./queryProvider";
import Navbar from "@/components/ui/Header/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <EnsureUserInDB>
        <QueryProvider>
      <html lang="en">
        <body
          className={`${inter.variable} antialiased `}
        >
          <Navbar/>
          <div>
          {children}

          </div>
        </body>
      </html>
      </QueryProvider>
      </EnsureUserInDB>
    </ClerkProvider>
  );
}
